### ISSUE TITLE
Updated bot to latest version and now can not find Haggis.

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#21]
I do not even know why, or how. But the bot seems to have turned Scottish and is demand a module called haggis after updating and will not start. Console log below:

```
Traceback (most recent call last):
File "/home/amp/.ampdata/instances/HiveMasterV2/gatekeeperv2/GatekeeperV2-main/start.py", line 87, in <module>
Start = Setup()
File "/home/amp/.ampdata/instances/HiveMasterV2/gatekeeperv2/GatekeeperV2-main/start.py", line 43, in __init__
import logger
File "/home/amp/.ampdata/instances/HiveMasterV2/gatekeeperv2/GatekeeperV2-main/logger.py", line 25, in <module>
from haggis import logs
ModuleNotFoundError: No module named 'haggis'
```

**Comment by k8thekat** [comment]
Just fixed the issue in the most recent PR. 

My apologies.
