### ISSUE TITLE
Not able to load

### ISSUE THREAD

**Issue by xLeviNx** [k8thekat/GatekeeperV2#23]
Installed all the necessary requirements for GateKeeperv2 via Amp

After updating all the settings, getting the following error

>start.py: error: unrecognized arguments: 988881855212302357

That is the guild ID of the server

**Comment by xLeviNx** [comment]
Logs provide the following error

`[01:00:05] [Generic:levin Warning] : The application stopped unexpectedly. Exit code 2
[01:00:08] [Generic:levin Info] Â Â : Writing config file ./gatekeeperv2/GatekeeperV2-main/tokens.py using Unicode (UTF-8) encoding.
usage: start.py [-h] [-token] [-super] [-dev] [-command] [-discord] [-debug]
start.py: error: unrecognized arguments: 988881855212302357
[01:00:08] [Generic:levin Warning] : The application stopped unexpectedly. Exit code 2
[01:00:11] [Generic:levin Info] Â Â : Writing config file ./gatekeeperv2/GatekeeperV2-main/tokens.py using Unicode (UTF-8) encoding.
usage: start.py [-h] [-token] [-super] [-dev] [-command] [-discord] [-debug]
start.py: error: unrecognized arguments: 988881855212302357
[01:00:11] [Generic:levin Warning] : The application stopped unexpectedly. Exit code 2
[01:00:14] [Generic:levin Info] Â Â : Writing config file ./gatekeeperv2/GatekeeperV2-main/tokens.py using Unicode (UTF-8) encoding.
usage: start.py [-h] [-token] [-super] [-dev] [-command] [-discord] [-debug]
start.py: error: unrecognized arguments: 988881855212302357
[01:00:14] [Generic:levin Warning] : The application stopped unexpectedly. Exit code 2
[01:00:14] [Generic:levin Warning] : Application failed to start 5 times, not restarting.
`

**Comment by k8thekat** [comment]
Hey,

Thanks for reporting the issue, I should have mentioned in the update notes
better. You do not need to supply your GuildID as a launch argument anymore.

Remove your guildID and start the bot like normal and it should work like
before.

I do recommend calling the "/bot sync" command so any future updates and
command additions are automatically synced when the bot starts.


Thanks!

**Comment by k8thekat** [comment]
Hey, it appears you have your URL for your AMP console inside the token file incorrect.

Please double check your AMP URL again.

**Comment by xLeviNx** [comment]
Tried both local IP and the link to my amp web gui. Does not work. Leads to the same error above


> 
Requirement already satisfied: GitPython>=3.1.27 in /home/amp/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (3.1.27)
Requirement already satisfied: nbtlib>=2.0.4 in /home/amp/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: pyotp>=2.6.0 in /home/amp/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: requests>=2.27.0 in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (2.28.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (1.23.1)
Requirement already satisfied: haggis in /home/amp/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.5.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/amp/.local/lib/python3.9/site-packages (from GitPython>=3.1.27->-r requirements.txt (line 1)) (4.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests>=2.27.0->-r requirements.txt (line 4)) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.9/dist-packages (from requests>=2.27.0->-r requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests>=2.27.0->-r requirements.txt (line 4)) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests>=2.27.0->-r requirements.txt (line 4)) (2022.6.15)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/amp/.local/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.27->-r requirements.txt (line 1)) (5.0.0)
21:39:45
Traceback (most recent call last):
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 431, in CallAPI
post_req = requests.post(self.url+APICall, headers=self.AMPheader, data=jsonhandler)
File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 115, in post
return request("post", url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 573, in request
prep = self.prepare_request(req)
File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 484, in prepare_request
p.prepare(
File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 368, in prepare
self.prepare_url(url, params)
File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 445, in prepare_url
raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'http:66.23.204.242:8080/API/Core/Login': No host supplied
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 408, in Login
result = self.CallAPI('Core/Login',parameters)
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 446, in CallAPI
sys.exit(-1)
SystemExit: -1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/AMP/gatekeeperv2/GatekeeperV2-main/start.py", line 89, in <module>
Start = Setup()
File "/AMP/gatekeeperv2/GatekeeperV2-main/start.py", line 69, in __init__
self.AMPHandler.setup_AMPInstances()
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 89, in setup_AMPInstances
self.AMP = AMPInstance(Handler = self)
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 260, in __init__
if self.check_AMPpermissions(): #We either have to have super or our bot role perms has been set manually!
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 332, in check_AMPpermissions
check = self.CurrentSessionHasPermission(perm)
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 769, in CurrentSessionHasPermission
self.Login()
File "/AMP/gatekeeperv2/GatekeeperV2-main/AMP.py", line 414, in Login
self.logger.warning(f'{self.FriendlyName} - Instance is Offline')
AttributeError: 'AMPInstance' object has no attribute 'FriendlyName'

**Comment by xLeviNx** [comment]
Ah fixed it.

The trailing / causes it to not work

>http://127.0.0.1:8080/

must be

>http://127.0.01:8080
