### ISSUE TITLE
Bot Runs, but does not show up online in discord

### ISSUE THREAD

**Issue by xLeviNx** [k8thekat/GatekeeperV2#24]
After having the bot setup and running, it does not show up online on the guild. The bot was manually added. Get the following issues in console log

>08/12/2022 01:56:17 AM [MainThread] [INFO] Bot Intializing...
08/12/2022 01:56:17 AM [MainThread] [INFO] Discord Version: 2.0.0a // Bot Version: beta-1.2.0 // Python Version 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
[2022-08-12 01:56:17] [INFO ] discord.client: logging in using static token
08/12/2022 01:56:17 AM [MainThread] [INFO] logging in using static token
08/12/2022 01:56:17 AM [MainThread] [INFO] Setting Up the Parser...
08/12/2022 01:56:17 AM [MainThread] [INFO] **SUCCESS** Initializing AMP_cog.py
08/12/2022 01:56:17 AM [MainThread] [INFO] **SUCCESS** Initializing **DB_cog.py**
08/12/2022 01:56:17 AM [MainThread] [INFO] **SUCCESS** Initializing... Loader.py
Traceback (most recent call last):
File "/AMP/gatekeeperv2/GatekeeperV2-main/start.py", line 94, in <module>
discordBot.client_run()
File "/AMP/gatekeeperv2/GatekeeperV2-main/discordBot.py", line 193, in client_run
client.run(tokens.token, reconnect = True)
File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 882, in run
asyncio.run(runner())
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 857, in runner
await self.start(token, reconnect=reconnect)
File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 790, in start
await self.login(token)
File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 642, in login
await self.setup_hook()
File "/AMP/gatekeeperv2/GatekeeperV2-main/discordBot.py", line 47, in setup_hook
await initbot()
File "/AMP/gatekeeperv2/GatekeeperV2-main/discordBot.py", line 187, in initbot
await Handler.module_auto_loader()
File "/AMP/gatekeeperv2/GatekeeperV2-main/loader.py", line 60, in module_auto_loader
await self._client.load_extension('modules.Generic.generic')
File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 993, in load_extension
raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'modules.Generic.generic' could not be loaded.

**Comment by k8thekat** [comment]
Hey, It appears I made a typo for when I changed a naming convention of my files.

Please rename your `/Modules/Generic/Generic.py` to a lowercase **generic.py**

Thanks!

**Comment by xLeviNx** [comment]
Nice!
