### ISSUE TITLE
Issue with setup command

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/GatekeeperV2#4]
Using latest version, via AMP install.
Attempting to use /setup command to set the staff role and it does not seem to work 
Input via discord is:
$bot setup (roleid)

Output via console is as follows:
```
08/01/2022 02:59:42 AM [MainThread] [ERROR] Ignoring exception in command bot setup
[2022-08-01 02:59:42] [ERROR ] discord.ext.commands.bot: Ignoring exception in command bot setup
Traceback (most recent call last):
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 195, in wrapped
ret = await coro(*args, **kwargs)
Traceback (most recent call last):
File "/home/amp/.ampdata/instances/AMPbot/gatekeeperv2/GatekeeperV2-main/discordBot.py", line 114, in bot_setup
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 195, in wrapped
guild_role = utils.botUtils.roleparse(staff_role,context,context.guild.id)
ret = await coro(*args, **kwargs)
TypeError: botUtils.roleparse() missing 1 required positional argument: 'guild_id'
File "/home/amp/.ampdata/instances/AMPbot/gatekeeperv2/GatekeeperV2-main/discordBot.py", line 114, in bot_setup
The above exception was the direct cause of the following exception:
guild_role = utils.botUtils.roleparse(staff_role,context,context.guild.id)
Traceback (most recent call last):
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
TypeError: botUtils.roleparse() missing 1 required positional argument: 'guild_id'
await ctx.command.invoke(ctx)
The above exception was the direct cause of the following exception:
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1609, in invoke
Traceback (most recent call last):
await ctx.invoked_subcommand.invoke(ctx)
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 990, in invoke
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1330, in invoke
await injected(*ctx.args, **ctx.kwargs) # type: ignore
await ctx.command.invoke(ctx)
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 204, in wrapped
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1609, in invoke
await ctx.invoked_subcommand.invoke(ctx)
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 990, in invoke
raise CommandInvokeError(exc) from exc
await injected(*ctx.args, **ctx.kwargs) # type: ignore
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: botUtils.roleparse() missing 1 required positional argument: 'guild_id'
File "/home/amp/.local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 204, in wrapped
raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: botUtils.roleparse() missing 1 required positional argument: 'guild_id'
```

**Comment by k8thekat** [comment]
Thanks for the report.

This issue was fixed in the most recent commit "6754f05c9b7d65b6eb69713e549d14416d073e33"

Please update your files.
Thanks.
