### ISSUE TITLE
Hanging and non-responsive when starting the bot

### ISSUE THREAD

**Issue by Acheronx98** [k8thekat/GatekeeperV2#59]
Anytime when trying to restart the bot, it doesn't want to accept any commands, hangs, and isn't responsive. Attached is my log (tokens.py exists, I just copied and left the template there so please ignore that line, I also edited out any instance id numbers or session numbers)

```
python3 ./start.py
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: aiohttp==3.7.4.post0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.7.4.post0)
Requirement already satisfied: async-timeout==3.0.1 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (3.0.1)
Requirement already satisfied: attrs==21.4.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (21.4.0)
Requirement already satisfied: certifi==2021.10.8 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (2021.10.8)
Requirement already satisfied: chardet==4.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: charset-normalizer==2.0.10 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.0.10)
Requirement already satisfied: docopt==0.6.2 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.6.2)
Requirement already satisfied: ffmpeg-python==0.2.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (0.2.0)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 9)) (0.18.2)
Requirement already satisfied: gitdb==4.0.9 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (4.0.9)
Requirement already satisfied: GitPython==3.1.27 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (3.1.27)
Requirement already satisfied: haggis==0.5.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (0.5.0)
Requirement already satisfied: idna==3.3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 13)) (3.3)
Requirement already satisfied: imageio-ffmpeg==0.4.7 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (0.4.7)
Requirement already satisfied: multidict==5.2.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (5.2.0)
Requirement already satisfied: nbtlib==2.0.4 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (2.0.4)
Requirement already satisfied: numpy==1.22.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (1.22.0)
Requirement already satisfied: Pillow>=9.2.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (9.3.0)
Requirement already satisfied: pipreqs==0.4.11 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 19)) (0.4.11)
Requirement already satisfied: pyotp==2.6.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 20)) (2.6.0)
Requirement already satisfied: python-dotenv==0.19.2 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 21)) (0.19.2)
Requirement already satisfied: requests==2.27.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 22)) (2.27.0)
Requirement already satisfied: smmap==5.0.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 23)) (5.0.0)
Requirement already satisfied: typing_extensions==4.0.1 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 24)) (4.0.1)
Requirement already satisfied: urllib3==1.26.7 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 25)) (1.26.7)
Requirement already satisfied: yarg==0.1.9 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 26)) (0.1.9)
Requirement already satisfied: yarl==1.7.2 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 27)) (1.7.2)
Requirement already satisfied: discord.py>=2.0.0 in /home/amp/.local/lib/python3.10/site-packages (from -r requirements.txt (line 28)) (2.1.0)
01/05/2023 03:53:05 PM [Gatekeeper] [INFO]  DB Handler Initialization...DB Version: 2.6
01/05/2023 03:53:05 PM [Gatekeeper] [INFO]  SQL Database Version: 2.6 // SQL Database: True
01/05/2023 03:53:05 PM [AMP] [INFO]  AMPHandler is validating your token file...
01/05/2023 03:53:05 PM [AMP] [CRITICAL]  **ERROR** Please rename your tokenstemplate.py file to tokens.py before trying again.
01/05/2023 03:53:05 PM [AMP] [WARNING]  Checking Session: 0 for proper permissions...
01/05/2023 03:53:09 PM [AMP] [INFO]  We have proper permissions on AMP
01/05/2023 03:53:09 PM [AMP] [INFO]  **SUCCESS** Found Server101 in the Database.
01/05/2023 03:53:09 PM [AMP] [INFO]  **SUCCESS** Found Valheim01 in the Database.
01/05/2023 03:53:10 PM [AMP] [WARNING]  Checking Session: * for proper permissions...
01/05/2023 03:53:10 PM [AMP] [INFO]  We have proper permissions on Valheim
01/05/2023 03:53:10 PM [AMP] [INFO]  **SUCCESS** Found Veloren01 in the Database.
01/05/2023 03:53:10 PM [AMP] [INFO]  **SUCCESS** Found Stoneblock301 in the Database.
01/05/2023 03:53:10 PM [AMP] [ERROR]  We failed to add the ConanExiles01 * to the DB. Error: table Servers has no column named FriendlyName
01/05/2023 03:53:10 PM [AMP] [INFO]  *SUCCESS** Added ConanExiles01 to the Database.
Exception in thread AMP:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amp/DiscordBot/AMP.py", line 50, in AMP_init
    handler.setup_AMPInstances() 
  File "/home/amp/DiscordBot/AMP.py", line 1053, in setup_AMPInstances
    self.getAMPInstances(amp= self.AMP)
  File "/home/amp/DiscordBot/AMP.py", line 1176, in getAMPInstances
    server = self.AMP_Modules['Generic'](instanceID= amp_instance['InstanceID'], serverdata= amp_instance, Handler= self, TargetName= Target['FriendlyName'])
  File "/home/amp/DiscordBot/modules/Generic/amp_generic.py", line 31, in __init__
    super().__init__(instanceID, serverdata, Handler=Handler, TargetName=TargetName)
  File "/home/amp/DiscordBot/AMP.py", line 193, in __init__
    self._setDBattr()
  File "/home/amp/DiscordBot/AMP.py", line 368, in _setDBattr
    self.DisplayName = self.DB_Server.DisplayName
AttributeError: 'NoneType' object has no attribute 'DisplayName'
Exception in thread Valheim:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amp/DiscordBot/AMP.py", line 1308, in console_parse
    if self.console_filter(entry):
  File "/home/amp/DiscordBot/AMP.py", line 1367, in console_filter
    regex = self.DB_Server.GetServerRegexPatterns()
  File "/home/amp/DiscordBot/DB.py", line 851, in GetServerRegexPatterns
    (rows, cur) = self._db._fetchall("SELECT RP.ID, RP.Name, RP.Type, RP.Pattern FROM ServerRegexPatterns SRP, RegexPatterns RP WHERE SRP.ServerID=? and SRP.RegexPatternID = RP.ID", (self.ID,))
  File "/home/amp/DiscordBot/DB.py", line 251, in _fetchall
    cur.execute(SQL, params)
sqlite3.OperationalError: no such table: ServerRegexPatterns


```

**Comment by k8thekat** [comment]
It appears you DB didn't properly populate its tables and columns.
`01/05/2023 03:53:10 PM [AMP] [ERROR]  We failed to add the ConanExiles01 * to the DB. Error: table Servers has no column named FriendlyName`

If you can send me a copy of your DB and then delete the `discordBot.db` file and restart the bot. Also make sure you are up to date.
